<main class="bg-store-soft py-6 sm:py-8">
    <x-store.ui.container>
        <div class="grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]">
            <x-store.account.sidebar />
            <div>
                <nav aria-label="Breadcrumb" class="mb-5 text-xs text-store-muted"><x-ui.breadcrumbs class="flex flex-wrap items-center gap-2"><x-ui.breadcrumbs.item href="{{ route('store.home') }}" wire:navigate>Home</x-ui.breadcrumbs.item><x-ui.breadcrumbs.item href="{{ route('account.orders') }}" wire:navigate>My Orders</x-ui.breadcrumbs.item><x-ui.breadcrumbs.item aria-current="page">{{ $orderModel->order_number }}</x-ui.breadcrumbs.item></x-ui.breadcrumbs></nav>
                <div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-extrabold tracking-tight text-store-ink sm:text-3xl">Order #{{ $orderModel->order_number }}</h1><p class="mt-1 text-sm text-store-muted">Placed {{ optional($orderModel->placed_at)->format('F j, Y g:i A') }}</p></div><span class="rounded-full bg-store-blue-soft px-3 py-1 text-sm font-bold capitalize text-store-blue">{{ $orderModel->status }}</span></div>
                <div class="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]"><section class="rounded-card border border-store-border bg-white p-5"><h2 class="text-lg font-extrabold text-store-ink">Items</h2><div class="mt-4 divide-y divide-store-border">@foreach($orderModel->items as $item)<div class="flex items-center justify-between gap-4 py-4 first:pt-0"><div><p class="text-sm font-bold text-store-ink">{{ $item->product_name }}</p><p class="mt-1 text-xs text-store-muted">{{ $item->variant_name ?: $item->sku }} · Qty {{ $item->quantity }}</p></div><span class="text-sm font-bold text-store-ink">৳{{ number_format($item->line_total_minor / 100, 2) }}</span></div>@endforeach</div></section><aside class="h-fit rounded-card border border-store-border bg-white p-5"><h2 class="text-lg font-extrabold text-store-ink">Summary</h2><div class="mt-4 space-y-2 text-sm"><div class="flex justify-between"><span class="text-store-muted">Subtotal</span><span>৳{{ number_format($orderModel->subtotal_minor / 100, 2) }}</span></div><div class="flex justify-between"><span class="text-store-muted">Delivery</span><span>৳{{ number_format($orderModel->shipping_minor / 100, 2) }}</span></div>@if($orderModel->discount_minor > 0)<div class="flex justify-between font-semibold text-emerald-600"><span>Coupon{{ $orderModel->coupon_code ? ' ('.$orderModel->coupon_code.')' : '' }}</span><span>-৳{{ number_format($orderModel->discount_minor / 100, 2) }}</span></div>@endif<div class="flex justify-between font-bold"><span>Total</span><span class="text-store-red">৳{{ number_format($orderModel->total_minor / 100, 2) }}</span></div></div><div class="mt-5 border-t border-store-border pt-4 text-sm"><p class="font-bold text-store-ink">Delivery address</p><p class="mt-1 text-store-muted">{{ $orderModel->shippingAddress?->name }}<br>{{ $orderModel->shippingAddress?->address_line }}<br>{{ $orderModel->shippingAddress?->city }}</p></div><a href="{{ route('account.tracking', ['order' => $orderModel->order_number]) }}" wire:navigate class="mt-5 inline-flex h-10 w-full items-center justify-center rounded-control bg-store-blue text-sm font-bold text-white">Track Order</a></aside></div>
            </div>
        </div>
    </x-store.ui.container>
</main>
