<?php
namespace App\Services;
use App\Enums\InventoryMovementType; use App\Models\{InventoryItem,ProductVariant}; use Illuminate\Support\Facades\DB; use InvalidArgumentException;
class InventoryService
{
    public function initialize(ProductVariant $variant, int $quantity=0): InventoryItem { return DB::transaction(function() use($variant,$quantity){ $item=InventoryItem::firstOrCreate(['product_variant_id'=>$variant->id],['quantity_on_hand'=>0]); if($quantity!==0) $this->record($item,$variant,$quantity,InventoryMovementType::Initial->value); return $item->fresh(); }); }
    public function adjust(ProductVariant $variant,int $delta,string $type='adjustment',?string $note=null): InventoryItem { return DB::transaction(function() use($variant,$delta,$type,$note){ $item=InventoryItem::firstOrCreate(['product_variant_id'=>$variant->id]); return $this->record($item,$variant,$delta,$type,$note); }); }
    public function reserve(ProductVariant $variant,int $quantity): InventoryItem { return DB::transaction(function() use($variant,$quantity){ $item=InventoryItem::lockForUpdate()->firstOrCreate(['product_variant_id'=>$variant->id]); if($item->track_quantity && $item->availableQuantity()<$quantity && !$item->allow_backorders) throw new InvalidArgumentException('Insufficient stock.'); $before=$item->quantity_reserved; $item->quantity_reserved += $quantity; $item->save(); $this->movement($item,$variant,$quantity,$before,$item->quantity_reserved,'reservation'); return $item; }); }
    public function release(ProductVariant $variant,int $quantity): InventoryItem { return DB::transaction(function() use($variant,$quantity){ $item=InventoryItem::lockForUpdate()->where('product_variant_id',$variant->id)->firstOrFail(); $before=$item->quantity_reserved; $item->quantity_reserved=max(0,$before-$quantity); $item->save(); $this->movement($item,$variant,$item->quantity_reserved-$before,$before,$item->quantity_reserved,'release'); return $item; }); }
    private function record(InventoryItem $item,ProductVariant $variant,int $delta,string $type,?string $note=null): InventoryItem { $item=InventoryItem::lockForUpdate()->find($item->id); $before=$item->quantity_on_hand; $after=$before+$delta; if($after<0 && !$item->allow_backorders) throw new InvalidArgumentException('Stock cannot become negative.'); $item->quantity_on_hand=$after; $item->save(); $this->movement($item,$variant,$delta,$before,$after,$type,$note); return $item->fresh(); }
    private function movement(InventoryItem $item,ProductVariant $variant,int $delta,int $before,int $after,string $type,?string $note=null): void { InventoryMovementType::tryFrom($type) ?? throw new InvalidArgumentException('Invalid inventory movement type.'); $item->movements()->create(['product_variant_id'=>$variant->id,'type'=>$type,'quantity_delta'=>$delta,'quantity_before'=>$before,'quantity_after'=>$after,'note'=>$note,'created_by'=>auth()->id()]); }
}
