<div class="p-5 sm:p-8">
    <div class="mx-auto max-w-[1480px]">
        <x-admin.cms.page-header eyebrow="StoreZ / Content / Redirects" title="Redirect manager" description="Protect SEO and customer journeys when storefront paths change."><x-slot:actions><a href="{{ url('/admin/content/redirects/export') }}" class="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700"><x-ui.icon name="arrow-down-tray" class="size-4" /> Export CSV</a></x-slot:actions></x-admin.cms.page-header>
        @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <div class="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($stats as $label => $value)<x-admin.cms.stat-card :label="$label" :value="number_format($value)" accent="blue" />@endforeach</div>
        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
            <div class="space-y-5">
                <x-admin.cms.panel title="Redirects" description="Edit destinations and identify disabled or chained redirects.">
                    <div class="mb-4"><input wire:model.live.debounce.300ms="search" placeholder="Search source paths or destinations..." class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"></div>
                    <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-slate-100 text-[11px] uppercase tracking-wide text-slate-400"><tr><th class="px-3 py-3">Source</th><th class="px-3 py-3">Destination</th><th class="px-3 py-3">Code</th><th class="px-3 py-3">Health</th><th class="px-3 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($redirects as $redirect)<tr wire:key="redirect-{{ $redirect->id }}" class="hover:bg-slate-50"><td class="px-3 py-4 font-bold text-slate-800">{{ $redirect->from_path }}</td><td class="max-w-xs truncate px-3 py-4 text-slate-600">{{ $redirect->to_url }}</td><td class="px-3 py-4"><x-admin.cms.badge tone="info">{{ $redirect->status_code }}</x-admin.cms.badge></td><td class="px-3 py-4">@if(isset($health[$redirect->id]))<x-admin.cms.badge tone="warning">{{ implode(', ', $health[$redirect->id]) }}</x-admin.cms.badge>@else<x-admin.cms.badge tone="success">Healthy</x-admin.cms.badge>@endif</td><td class="px-3 py-4 text-right"><button wire:click="editRedirect({{ $redirect->id }})" class="font-bold text-blue-600">Edit</button><button wire:click="deleteRedirect({{ $redirect->id }})" wire:confirm="Delete this redirect?" class="ml-3 font-bold text-red-600">Delete</button></td></tr>@empty<tr><td colspan="5" class="px-3 py-14 text-center text-sm text-slate-500">No redirects match your search.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $redirects->links() }}</div>
                </x-admin.cms.panel>
            </div>
            <div class="space-y-5">
                <x-admin.cms.panel :title="$editingId ? 'Edit redirect' : 'Add redirect'" description="Use a relative source path and a validated destination."><div class="space-y-3"><label class="block text-sm font-semibold text-slate-700">From path<input wire:model.live="from_path" placeholder="/old-path" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold text-slate-700">To URL<input wire:model.live="to_url" placeholder="/new-path or https://..." class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold text-slate-700">Status code<select wire:model.live="status_code" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option>301</option><option>302</option><option>307</option><option>308</option></select></label><label class="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" wire:model.live="enabled" class="rounded border-slate-300 text-blue-600"> Enabled</label><div class="flex gap-2"><button wire:click="saveRedirect" wire:loading.attr="disabled" class="flex-1 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{{ $editingId ? 'Update redirect' : 'Save redirect' }}</button>@if($editingId)<button wire:click="cancelEdit" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-600">Cancel</button>@endif</div></div></x-admin.cms.panel>
                <x-admin.cms.panel title="Import CSV" description="Imports are validated before any rows are written."><input type="file" wire:model="file" accept=".csv,.txt" class="w-full text-xs text-slate-500"><button wire:click="importRedirects" wire:loading.attr="disabled" class="mt-3 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-700 disabled:opacity-60">Import redirects</button></x-admin.cms.panel>
            </div>
        </div>
    </div>
</div>
