<div class="min-h-[calc(100vh-72px)] bg-[#f7f9fc] px-5 py-7 text-[#17233d] sm:px-8">
    <div class="mx-auto max-w-[1480px]">
        <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="mb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#9aa8bd]">Catalog / Management</p><h1 class="text-[30px] font-extrabold tracking-[-.7px]">{{ $title }}</h1><p class="mt-1 text-sm text-[#718099]">Keep your store taxonomy organized and easy to manage.</p></div><a href="{{ url('/admin/catalog/products/create') }}" class="rounded-lg bg-[#1769e8] px-4 py-2.5 text-center text-sm font-bold text-white shadow-[0_5px_12px_rgba(23,105,232,.2)]">Add product</a></div>
        <div class="mb-6 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border border-[#e3e9f2] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.04)]"><p class="text-xs font-semibold text-[#718099]">Total {{ $title }}</p><p class="mt-2 text-[28px] font-extrabold">{{ $rows->total() }}</p><p class="mt-1 text-xs text-[#9aa8bd]">Available in this workspace</p></div><div class="rounded-xl border border-[#e3e9f2] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.04)]"><p class="text-xs font-semibold text-[#718099]">Selected</p><p class="mt-2 text-[28px] font-extrabold text-[#1769e8]">{{ count($selected) }}</p><p class="mt-1 text-xs text-[#9aa8bd]">Ready for bulk actions</p></div><div class="rounded-xl border border-[#e3e9f2] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.04)]"><p class="text-xs font-semibold text-[#718099]">Last updated</p><p class="mt-2 text-lg font-extrabold">Just now</p><p class="mt-1 text-xs text-[#9aa8bd]">Changes save automatically</p></div></div>
        <div class="mb-4 rounded-xl border border-[#e3e9f2] bg-white p-4 shadow-[0_3px_12px_rgba(30,55,90,.04)]"><form wire:submit="createRecord" class="flex flex-col gap-3 md:flex-row"><x-ui.input wire:model="name" placeholder="Create a new {{ strtolower($title) }}..." class="h-11 flex-1 !rounded-lg" controlClass="!rounded-lg !border-[#e0e6ef] !bg-[#fbfcfe]" /><button class="h-11 rounded-lg bg-[#17233d] px-5 text-sm font-bold text-white">Create {{ strtolower($title) }}</button></form></div>
        <div class="mb-4 flex flex-col gap-3 rounded-xl border border-[#e3e9f2] bg-white p-3 shadow-[0_3px_12px_rgba(30,55,90,.04)] sm:flex-row"><x-ui.input wire:model.live.debounce.300ms="search" leftIcon="magnifying-glass" placeholder="Search {{ strtolower($title) }}..." class="min-w-0 flex-1 !rounded-lg" controlClass="!rounded-lg !border-[#e0e6ef]" /><x-ui.select wire:model.live="perPage" placeholder="15" class="h-10 sm:w-24"><x-ui.select.option value="15">15</x-ui.select.option><x-ui.select.option value="30">30</x-ui.select.option><x-ui.select.option value="50">50</x-ui.select.option></x-ui.select></div>
        @if(count($selected))<div class="mb-4 rounded-xl border border-[#cfe0ff] bg-[#f1f6ff] p-3 text-sm font-semibold text-[#1769e8]">{{ count($selected) }} {{ strtolower($title) }} selected</div>@endif
        <div class="overflow-hidden rounded-xl border border-[#e3e9f2] bg-white shadow-[0_3px_12px_rgba(30,55,90,.04)]"><div class="flex items-center justify-between border-b border-[#edf1f6] px-5 py-4"><div><h2 class="font-bold">{{ $title }} list</h2><p class="mt-1 text-xs text-[#9aa8bd]">Review and manage all records.</p></div><span class="rounded-full bg-[#e7f0ff] px-3 py-1 text-xs font-bold text-[#1769e8]">{{ $rows->total() }} records</span></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-[#fbfcfe] text-[11px] font-bold uppercase tracking-[.08em] text-[#9aa8bd]"><tr><th class="w-12 px-5 py-3"><input type="checkbox" wire:click="togglePageSelection" class="rounded border-[#cbd5e1] text-[#1769e8]"></th><th class="px-4 py-3">Name</th><th class="px-4 py-3">Slug</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Updated</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-[#edf1f6]">@forelse($rows as $row)<tr class="group hover:bg-[#fbfdff]"><td class="px-5 py-4"><input type="checkbox" wire:model="selected" value="{{ $row->id }}" class="rounded border-[#cbd5e1] text-[#1769e8]"></td><td class="px-4 py-4"><div class="flex items-center gap-3"><div class="grid size-10 place-items-center rounded-lg bg-[#f1f6ff] text-[#1769e8]"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5"/></svg></div><span class="font-bold text-[#263550]">{{ $row->name }}</span></div></td><td class="px-4 py-4 text-[#718099]">{{ $row->slug }}</td><td class="px-4 py-4"><span class="rounded-full bg-[#e7f8ef] px-2.5 py-1 text-[11px] font-bold text-[#159669]">{{ is_object($row->status ?? null) ? ucfirst($row->status->value) : (($row->is_active ?? true) ? 'Active' : 'Inactive') }}</span></td><td class="px-4 py-4 text-[#718099]">{{ $row->updated_at?->diffForHumans() }}</td><td class="px-5 py-4 text-right"><button wire:click="delete({{ $row->id }})" wire:confirm="Delete this record?" class="font-semibold text-[#e05252] opacity-0 transition group-hover:opacity-100">Delete</button></td></tr>@empty<tr><td colspan="6" class="px-5 py-16 text-center"><p class="font-bold text-[#53627b]">No {{ strtolower($title) }} found</p><p class="mt-1 text-sm text-[#9aa8bd]">Create a record above to get started.</p></td></tr>@endforelse</tbody></table></div><div class="border-t border-[#edf1f6] px-5 py-4">{{ $rows->links() }}</div></div>
    </div>
</div>
