<main class="bg-store-soft py-6 sm:py-8">
    <x-store.ui.container>
        <x-store.ui.breadcrumb :items="[['label' => 'Shopping Cart']]" />
        <div class="flex items-end justify-between gap-4"><div><h1 class="text-2xl font-extrabold tracking-tight text-store-ink sm:text-3xl">Shopping Cart</h1><p class="mt-1 text-sm text-store-muted">{{ collect($items)->sum('quantity') }} items ready for checkout</p></div><a href="{{ route('store.category') }}" wire:navigate class="hidden text-sm font-semibold text-store-blue hover:underline sm:inline">Continue Shopping →</a></div>
        @if($errors->has('cart')) <div class="mt-4 rounded-control bg-red-50 p-4 text-sm text-red-700">{{ $errors->first('cart') }}</div> @endif
        <div class="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
            <section class="rounded-card border border-store-border bg-white">
                @forelse($items as $item)
                    <article wire:key="cart-item-{{ $item['id'] }}" class="grid gap-3 border-b border-store-border p-4 last:border-0 sm:grid-cols-[minmax(0,1fr)_130px_130px_40px] sm:items-center sm:gap-4 sm:px-5">
                        <div class="flex min-w-0 items-center gap-3"><img src="{{ $item['image'] }}" alt="{{ $item['name'] }}" class="size-20 shrink-0 rounded-control border border-store-border object-contain"><div class="min-w-0"><p class="line-clamp-2 text-sm font-bold text-store-ink">{{ $item['name'] }}</p>@if($item['variant']) <p class="mt-1 text-xs text-store-muted">{{ $item['variant'] }} · {{ $item['sku'] }}</p> @endif<p class="mt-1 text-sm font-extrabold text-store-red">৳{{ number_format($item['price'] / 100, 2) }}</p></div></div>
                        <div class="flex items-center justify-between sm:block"><span class="text-xs font-semibold text-store-muted sm:hidden">Quantity</span><div class="inline-flex h-9 items-center rounded-control border border-store-border"><button type="button" wire:click="updateItem({{ $item['id'] }}, {{ max(1, $item['quantity'] - 1) }})" class="grid size-9 place-items-center" aria-label="Decrease quantity">−</button><span class="w-8 text-center text-sm font-bold">{{ $item['quantity'] }}</span><button type="button" wire:click="updateItem({{ $item['id'] }}, {{ $item['quantity'] + 1 }})" class="grid size-9 place-items-center" aria-label="Increase quantity">+</button></div></div>
                        <div class="flex items-center justify-between sm:block sm:text-right"><span class="text-xs font-semibold text-store-muted sm:hidden">Subtotal</span><span class="text-sm font-extrabold text-store-red">৳{{ number_format($item['line_total'] / 100, 2) }}</span></div>
                        <button type="button" wire:click="removeItem({{ $item['id'] }})" class="text-left text-xs font-semibold text-store-error hover:underline sm:text-center">Remove</button>
                    </article>
                @empty
                    <div class="p-12 text-center"><x-ui.icon name="shopping-cart" class="mx-auto size-10 !text-store-placeholder" /><h2 class="mt-4 font-bold text-store-ink">Your cart is empty</h2><a href="{{ route('store.category') }}" wire:navigate class="mt-5 inline-flex h-10 items-center rounded-control bg-store-blue px-4 py-2 text-sm font-bold text-white">Start Shopping</a></div>
                @endforelse
            </section>
            <aside class="h-fit rounded-card border border-store-border bg-white p-5 lg:sticky lg:top-5"><h2 class="text-lg font-extrabold text-store-ink">Order Summary</h2><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between"><span class="text-store-muted">Subtotal</span><span class="font-semibold">৳{{ number_format($subtotal / 100, 2) }}</span></div><div class="flex justify-between"><span class="text-store-muted">Delivery fee</span><span class="font-semibold text-store-success">Calculated at checkout</span></div></div><div class="my-5 border-t border-store-border"></div><div class="flex justify-between text-lg font-extrabold text-store-ink"><span>Total</span><span>৳{{ number_format($subtotal / 100, 2) }}</span></div><a href="{{ route('store.checkout') }}" wire:navigate class="mt-5 inline-flex h-12 w-full items-center justify-center rounded-control bg-store-red text-sm font-bold text-white {{ empty($items) ? 'pointer-events-none opacity-50' : '' }}">Proceed to Checkout</a><p class="mt-3 text-center text-xs text-store-muted">Secure checkout · Cash on Delivery available</p></aside>
        </div>
    </x-store.ui.container>
</main>
