<main x-data="{ filtersOpen: false }" class="bg-store-soft py-6 sm:py-8">
    <x-store.ui.container>
        <x-store.ui.breadcrumb :items="[['label' => $categoryName]]" />
        <div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-extrabold tracking-tight text-store-ink sm:text-3xl">{{ $categoryName }}</h1><p class="mt-1 text-sm text-store-muted">Browse quality products at everyday StoreZ prices.</p></div><button type="button" class="inline-flex h-10 items-center gap-2 rounded-control border border-store-blue bg-white px-4 text-sm font-bold text-store-blue lg:hidden" @click="filtersOpen = true" aria-controls="category-filters" :aria-expanded="filtersOpen.toString()"><x-ui.icon name="adjustments-horizontal" class="size-4 !text-current" />Filters</button></div>
        <form method="GET" class="mt-6 grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]">
            <div x-cloak x-show="filtersOpen" x-transition.opacity class="fixed inset-0 z-30 bg-store-ink/45 lg:hidden" @click="filtersOpen = false" aria-hidden="true"></div>
            <aside id="category-filters" x-cloak x-show="filtersOpen || window.innerWidth >= 1024" x-transition class="fixed inset-y-0 left-0 z-40 h-auto w-[min(88vw,22rem)] overflow-y-auto rounded-none border-r border-store-border bg-white p-4 shadow-2xl lg:static lg:z-auto lg:block lg:h-fit lg:w-auto lg:rounded-card lg:border lg:shadow-none" @keydown.escape.window="filtersOpen = false">
                <div class="flex items-center justify-between"><h2 class="font-bold text-store-ink">Filters</h2><div class="flex items-center gap-3"><a href="{{ route('store.category', ['slug' => $slug]) }}" class="text-xs font-semibold text-store-blue hover:underline">Clear all</a><button type="button" class="lg:hidden" @click="filtersOpen = false" aria-label="Close filters"><x-ui.icon name="x-mark" class="size-5 !text-current" /></button></div></div>
                <div class="mt-5 space-y-5"><fieldset><legend class="text-sm font-bold text-store-ink">Categories</legend><div class="mt-3 space-y-2">@foreach($categories as $category)<a wire:navigate href="{{ route('store.category', ['slug' => $category['slug']]) }}" class="block text-sm {{ $slug === $category['slug'] ? 'font-bold text-store-blue' : 'text-store-text hover:text-store-blue' }}">{{ $category['name'] }}</a>@endforeach</div></fieldset><x-store.ui.filter-group title="Brands" name="brand" :options="$brands" :selected="$selectedBrands" /><x-store.ui.filter-group title="Availability" name="in_stock" :options="['In stock only']" :selected="request('in_stock') ? ['In stock only'] : []" /></div>
                <button class="mt-5 h-10 w-full rounded-control bg-store-blue text-sm font-bold text-white" @click="filtersOpen = false">Apply filters</button>
            </aside>
            <section><div class="flex flex-wrap items-center justify-between gap-3 rounded-card border border-store-border bg-white p-3"><p class="text-sm text-store-muted">Showing <span class="font-bold text-store-ink">{{ $products->total() }}</span> products</p><div class="flex items-center gap-2" x-data="{ selectedSort: @js($sort) }"><label class="text-xs font-semibold text-store-muted">Sort by</label><x-ui.select name="sort" x-model="selectedSort" size="sm" placeholder="Popularity" trigger-class="!bg-white !text-store-ink dark:!bg-white dark:!text-store-ink" @change="setTimeout(() => $el.closest('form').submit())" class="w-48"><x-ui.select.option value="popular">Popularity</x-ui.select.option><x-ui.select.option value="price_asc">Price: Low to High</x-ui.select.option><x-ui.select.option value="price_desc">Price: High to Low</x-ui.select.option><x-ui.select.option value="rating">Rating</x-ui.select.option></x-ui.select></div></div>
                <div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">@forelse($products as $product)<x-store.catalog.product-card wire:key="category-product-{{ $product['id'] }}" :product="$product" />@empty<div class="col-span-full rounded-card border border-store-border bg-white p-12 text-center text-sm text-store-muted">No products found for this category.</div>@endforelse</div><x-store.ui.pagination :current="$products->currentPage()" :total="$products->lastPage()" /></section>
        </form>
    </x-store.ui.container>
</main>
