@php
    $products = \App\Support\StorefrontDemoData::products();
    $categories = \App\Support\StorefrontDemoData::categories();
    $homepageCategories = \App\Support\StorefrontDemoData::homepageCategories();
    $categoryIcons = array_column($homepageCategories, 'icon');
    $categoryNames = array_column($homepageCategories, 'name');
    $brands = array_map(fn ($brand) => strtoupper($brand['name']), \App\Support\StorefrontDemoData::brands());
    $combos = \App\Support\StorefrontDemoData::combos();
@endphp

<x-layouts.app title="StoreZ — Shop Smarter">
    <main class="bg-white pb-10">
        <x-store.ui.container>
            <div class="grid gap-4 pt-5 lg:grid-cols-[220px_minmax(0,1fr)_280px]">
                <aside class="hidden rounded-card border border-store-border bg-white p-3 lg:block">
                    @foreach ($categoryNames as $index => $name)
                        <a href="{{ route('store.category') }}" wire:navigate class="flex items-center justify-between border-b border-store-border px-2 py-3 text-sm last:border-0 hover:text-store-blue"><span class="flex min-w-0 items-center gap-2"><x-ui.icon :name="$categoryIcons[$index]" class="size-4 shrink-0 !text-store-blue" /><span class="truncate">{{ $name }}</span></span><x-ui.icon name="chevron-right" class="size-4 !text-store-muted" /></a>
                    @endforeach
                </aside>

                <x-store.ui.carousel loop label="Featured promotions" :show-dots="false" :show-controls="false" class="min-w-0">
                    <article class="relative min-h-[340px] w-full shrink-0 overflow-hidden rounded-card bg-gradient-to-br from-[#0e55a8] via-[#063875] to-[#052b5d] p-7 text-white sm:p-10">
                    <div class="relative z-10 max-w-xl"><p class="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">StoreZ everyday value</p><h1 class="mt-3 text-4xl font-black leading-[1.05] sm:text-5xl">Back to<br>Better Deals<br><span class="text-yellow-300">Every Day!</span></h1><p class="mt-4 max-w-md text-base text-blue-100">Groceries, fashion, electronics & more at unbeatable prices.</p><a href="{{ route('store.offers') }}" wire:navigate class="mt-6 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-store-navy transition hover:bg-blue-50">Shop Now</a></div><div class="pointer-events-none absolute -right-12 -bottom-20 size-64 rounded-full bg-store-blue/70 blur-2xl sm:size-80"></div><x-ui.icon name="shopping-bag" class="pointer-events-none absolute right-10 top-10 size-32 !text-blue-200/30 sm:size-40" />
                    </article>
                    <article class="relative min-h-[340px] w-full shrink-0 overflow-hidden rounded-card bg-gradient-to-br from-[#b91c1c] via-[#dc2626] to-[#7f1d1d] p-7 text-white sm:p-10"><div class="relative z-10 max-w-xl"><p class="text-xs font-bold uppercase tracking-[0.2em] text-red-100">StoreZ fashion festival</p><h1 class="mt-3 text-4xl font-black leading-[1.05] sm:text-5xl">Fresh Looks<br><span class="text-yellow-300">Big Savings!</span></h1><p class="mt-4 max-w-md text-base text-red-100">Trending styles and everyday essentials at prices you’ll love.</p><a href="#offers" class="mt-6 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-red-700 transition hover:bg-red-50">Shop Fashion</a></div><x-ui.icon name="sparkles" class="pointer-events-none absolute right-10 top-10 size-32 !text-red-100/30 sm:size-40" /></article>
                    <article class="relative min-h-[340px] w-full shrink-0 overflow-hidden rounded-card bg-gradient-to-br from-[#047857] via-[#059669] to-[#064e3b] p-7 text-white sm:p-10"><div class="relative z-10 max-w-xl"><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-100">StoreZ fresh picks</p><h1 class="mt-3 text-4xl font-black leading-[1.05] sm:text-5xl">Everyday<br><span class="text-yellow-300">Essentials, Less!</span></h1><p class="mt-4 max-w-md text-base text-emerald-100">Stock up on groceries and home favorites with dependable delivery.</p><a href="#offers" class="mt-6 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-emerald-700 transition hover:bg-emerald-50">Shop Groceries</a></div><x-ui.icon name="shopping-cart" class="pointer-events-none absolute right-10 top-10 size-32 !text-emerald-100/30 sm:size-40" /></article>
                    <div class="pointer-events-none absolute bottom-7 left-7 z-20 flex gap-2 sm:bottom-10 sm:left-10" aria-label="Featured promotion slides"><template x-for="page in pageCount" :key="page"><button type="button" class="pointer-events-auto size-2 rounded-full transition-colors" :class="current === page - 1 ? 'bg-white' : 'bg-white/50'" @click="goTo(page - 1)" :aria-label="`Go to featured promotion ${page}`"></button></template></div>
                </x-store.ui.carousel>

                <x-store.ui.carousel loop label="Promotions" class="lg:min-w-0">
                    <article class="w-full shrink-0 rounded-card border border-store-border bg-blue-50 p-5"><h2 class="text-xl font-extrabold text-store-blue">Up to 40% Off<br>On Laptops</h2><p class="mt-2 text-xs text-store-muted">Top Brands | Warranty</p><a href="#offers" class="mt-4 inline-flex rounded-control bg-store-blue px-4 py-2 text-xs font-bold text-white hover:bg-store-blue-dark">Shop Now</a></article>
                    <article class="w-full shrink-0 rounded-card border border-store-border bg-red-50 p-5"><h2 class="text-xl font-extrabold text-store-red">Fashion Fest<br>Up to 60% Off</h2><p class="mt-2 text-xs text-store-muted">Trendy Looks, Lowest Prices</p><a href="#offers" class="mt-4 inline-flex rounded-control bg-store-red px-4 py-2 text-xs font-bold text-white hover:bg-red-700">Shop Now</a></article>
                    <article class="w-full shrink-0 rounded-card border border-store-border bg-amber-50 p-5"><h2 class="text-xl font-extrabold text-amber-700">Fresh Picks<br>Up to 30% Off</h2><p class="mt-2 text-xs text-store-muted">Daily essentials at better prices</p><a href="#offers" class="mt-4 inline-flex rounded-control bg-amber-600 px-4 py-2 text-xs font-bold text-white hover:bg-amber-700">Shop Now</a></article>
                </x-store.ui.carousel>
            </div>

            <section id="category" class="mt-8"><div class="mb-4 flex items-center justify-between"><h2 class="text-xl font-extrabold tracking-tight text-store-ink">Shop by Category</h2><a href="#categories" class="text-sm font-semibold text-store-blue hover:underline">View All →</a></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">@foreach ($categoryNames as $index => $name)<a href="#category" class="rounded-card border border-store-border bg-white p-3 text-center transition hover:-translate-y-0.5 hover:shadow-store-soft"><span class="mx-auto flex aspect-square w-full items-center justify-center rounded-control bg-store-soft px-2 text-center"><x-ui.icon :name="$categoryIcons[$index]" class="size-8 !text-store-blue" /></span><span class="mt-2 block text-xs font-semibold text-store-ink">{{ $name }}</span></a>@endforeach</div></section>

            <section id="offers" class="mt-8"><div class="mb-4 flex flex-wrap items-center justify-between gap-2"><div class="flex items-center gap-3"><h2 class="text-xl font-extrabold tracking-tight text-store-ink">Flash Sale</h2><span class="rounded bg-store-red/10 px-2 py-1 font-mono text-sm font-bold text-store-red">02 : 45 : 30</span><span class="hidden text-xs text-store-muted sm:inline">Hurry! Limited time offers</span></div><a href="#offers" class="text-sm font-semibold text-store-blue hover:underline">View All Deals →</a></div><div class="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">@foreach (array_slice($products, 3, 6) as $product)<x-store.catalog.product-card :product="$product" compact />@endforeach</div></section>

            <section class="mt-8 rounded-card border border-amber-200 bg-gradient-to-r from-amber-50 to-yellow-100 p-4 sm:p-5"><div class="flex items-end justify-between gap-3"><div><h2 class="text-xl font-extrabold text-store-ink">Smart Combo Deals</h2><p class="text-xs text-store-muted">More Items, More Savings!</p></div><a href="#offers" class="text-sm font-semibold text-store-blue hover:underline">View All Combos →</a></div><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">@foreach ($combos as $combo)<article class="flex items-center gap-3 rounded-card border border-store-border bg-white p-3"><img src="{{ asset('images/placeholders/no-image.svg') }}" alt="" class="size-20 object-contain"><div><h3 class="text-sm font-bold text-store-ink">{{ $combo['name'] }}</h3><p class="mt-1 font-extrabold text-store-red">৳{{ number_format($combo['price']) }}</p><p class="text-xs font-bold text-store-success">Save ৳{{ number_format($combo['save']) }}</p><button type="button" class="mt-2 rounded bg-store-blue px-3 py-1.5 text-[11px] font-bold text-white hover:bg-store-blue-dark" @click="cartOpen = true">Add to Cart</button></div></article>@endforeach</div></section>

            <section class="mt-8"><div class="mb-4 flex items-center justify-between"><h2 class="text-xl font-extrabold tracking-tight text-store-ink">Best Sellers</h2><a href="#category" class="text-sm font-semibold text-store-blue hover:underline">View All →</a></div><div class="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">@foreach (array_slice($products, 9, 6) as $product)<x-store.catalog.product-card :product="$product" compact />@endforeach</div></section>

            <section id="brands" class="mt-8"><div class="mb-4 flex items-center justify-between"><h2 class="text-xl font-extrabold tracking-tight text-store-ink">Top Brands You Trust</h2><a href="#brands" class="text-sm font-semibold text-store-blue hover:underline">View All Brands â†’</a></div><x-store.ui.carousel loop label="Top brands">@foreach ($brands as $brand)<article class="w-[calc((100%-0.75rem)/2)] shrink-0 sm:w-[calc((100%-2.25rem)/4)] lg:w-[calc((100%-3.75rem)/6)]"><a href="#brands" class="grid min-h-16 h-full place-items-center rounded-card border border-store-border bg-white p-3 text-center text-sm font-black text-store-blue transition hover:border-store-blue">{{ $brand }}</a></article>@endforeach</x-store.ui.carousel></section>

            <section class="mt-8"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-xl font-extrabold tracking-tight text-store-ink">Fresh Picks for You</h2><p class="text-xs text-store-muted">Handpicked trending items</p></div><a href="#category" class="text-sm font-semibold text-store-blue hover:underline">View All →</a></div><div class="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">@foreach (array_slice($products, 3, 6) as $product)<x-store.catalog.product-card :product="$product" compact />@endforeach</div></section>

            <section class="mt-8"><div class="mb-4 flex items-center justify-between"><h2 class="text-xl font-extrabold tracking-tight text-store-ink">What Our Customers Say</h2><span class="text-sm text-store-muted">Real feedback from StoreZ shoppers</span></div><x-store.ui.carousel loop label="Customer testimonials"><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Nusrat Jahan" quote="Great experience! Fast delivery and products were exactly as described. StoreZ is my new go-to shop." /><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Rafiq Ahmed" quote="Love the combo deals and COD option. Very convenient and trustworthy platform." /><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Tania Rahman" quote="Quality products, best prices and excellent customer service. Highly recommended." /><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Farhan Kabir" quote="The product selection is excellent and delivery updates made every order easy to follow." /><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Maliha Sultana" quote="I found exactly what I needed at a fair price, and the checkout was quick and simple." /><x-store.ui.testimonial-card class="w-[calc((100%-0rem)/1)] shrink-0 snap-start sm:w-[calc((100%-0.75rem)/2)] lg:w-[calc((100%-1.5rem)/3)]" name="Imran Hossain" quote="Fast service, helpful support, and reliable packaging. I’ll definitely shop from StoreZ again." /></x-store.ui.carousel></section>
        </x-store.ui.container>
    </main>
</x-layouts.app>
