<?php
namespace Tests\Feature;
use App\Models\User; use App\Services\{ProductExportService,ProductImportService,ProductService}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\Storage; use Tests\TestCase;
class AdminCatalogTest extends TestCase
{
    use RefreshDatabase;
    public function test_admin_routes_require_admin_user():void{$this->get('/admin')->assertRedirect('/login');$user=User::factory()->create(['is_admin'=>false]);$this->actingAs($user)->get('/admin')->assertForbidden();$admin=User::factory()->create(['is_admin'=>true]);$this->actingAs($admin)->get('/admin')->assertOk();}
    public function test_simple_product_creates_default_variant_and_inventory():void{$product=app(ProductService::class)->save(['name'=>'Test Headphones','product_type'=>'simple','status'=>'draft','regular_price_minor'=>4290]);$this->assertSame('STZ-'.$product->id,$product->defaultVariant->sku);$this->assertNotNull($product->defaultVariant->inventory);$this->assertSame(0,$product->defaultVariant->inventory->quantity_on_hand);}
    public function test_variable_options_generate_unique_variants():void{$product=app(ProductService::class)->save(['name'=>'Test Shirt','product_type'=>'variable','status'=>'draft','regular_price_minor'=>0]);$color=$product->options()->create(['name'=>'Color','slug'=>'color']);$size=$product->options()->create(['name'=>'Size','slug'=>'size']);$color->values()->createMany([['value'=>'Black','slug'=>'black'],['value'=>'White','slug'=>'white']]);$size->values()->createMany([['value'=>'S','slug'=>'s'],['value'=>'M','slug'=>'m']]);$variants=app(\App\Services\ProductVariantService::class)->generate($product);$this->assertCount(4,$variants);$this->assertCount(4,$product->fresh()->variants);}
    public function test_inventory_adjustment_is_audited():void{$product=app(ProductService::class)->save(['name'=>'Test Stock','product_type'=>'simple','status'=>'draft','regular_price_minor'=>100]);$item=app(\App\Services\InventoryService::class)->adjust($product->defaultVariant,5,'restock','Initial delivery');$this->assertSame(5,$item->quantity_on_hand);$this->assertSame(1,$item->movements()->count());$this->assertSame('restock',$item->movements()->first()->type);}
    public function test_csv_import_validates_and_creates_simple_product():void{Storage::fake('local');$file=UploadedFile::fake()->createWithContent('products.csv',"Product Name,SKU,Regular Price\nImported Lamp,IMP-001,12.50\n");$import=app(ProductImportService::class)->upload($file);$summary=app(ProductImportService::class)->validate($import);$this->assertSame(1,$summary['valid']);$result=app(ProductImportService::class)->import($import);$this->assertSame(1,$result['created']);$this->assertDatabaseHas('products',['name'=>'Imported Lamp']);$this->assertDatabaseHas('product_variants',['sku'=>'IMP-001']);}
    public function test_csv_export_writes_private_file_and_history():void{$product=app(ProductService::class)->save(['name'=>'Export Lamp','product_type'=>'simple','status'=>'draft','regular_price_minor'=>1250]);$export=app(ProductExportService::class)->export();$this->assertSame('ready',$export->status);$this->assertSame(1,$export->record_count);$this->assertFileExists(storage_path('app/private/'.$export->path));}
}
