<div class="min-h-[calc(100vh-72px)] bg-[#f7f9fc] px-5 py-7 text-[#17233d] sm:px-8">
    <div class="mx-auto max-w-[1480px]">
        <div class="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
            <div>
                <div class="mb-3 flex items-center gap-2 text-xs font-semibold text-[#1769e8]"><a href="{{ url('/admin') }}">Dashboard</a><span class="text-[#b2bdcc]">/</span><a href="{{ url('/admin/catalog/products') }}">Catalog</a><span class="text-[#b2bdcc]">/</span><span class="text-[#718099]">{{ $product?->exists ? 'Edit Product' : 'Add Product' }}</span></div>
                <h1 class="text-[30px] font-extrabold tracking-[-.7px]">{{ $product?->exists ? 'Edit Product' : 'Add New Product' }}</h1>
                <p class="mt-1 text-sm text-[#718099]">Create a new product and configure pricing, stock, and storefront information.</p>
            </div>
            <div class="flex flex-wrap gap-2">
                <a href="{{ url('/admin/catalog/products') }}" class="rounded-lg border border-[#dce4ef] bg-white px-4 py-2.5 text-sm font-semibold text-[#53627b]">Cancel</a>
                <button form="product-form" type="submit" class="rounded-lg bg-[#1769e8] px-5 py-2.5 text-sm font-bold text-white shadow-[0_5px_12px_rgba(23,105,232,.2)]">Save Product</button>
            </div>
        </div>

        @if (session('status')) <div class="mb-5 rounded-xl border border-[#bcebd7] bg-[#effcf5] p-3 text-sm font-semibold text-[#159669]">{{ session('status') }}</div> @endif
        @if ($errors->any()) <div class="mb-5 rounded-xl border border-[#ffd5d5] bg-[#fff6f6] p-4 text-sm text-[#c24141]"><p class="font-bold">Please check the form</p><ul class="mt-1 list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif

        <form id="product-form" wire:submit="saveProduct" class="grid items-start gap-5 lg:grid-cols-[minmax(0,1.65fr)_270px_320px]">
            <div class="space-y-5">
                <section class="rounded-xl border border-[#dfe6ef] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.03)] sm:p-6">
                    <div class="mb-5 flex items-center justify-between"><div><h2 class="font-bold text-[#17233d]">Basic Information</h2><p class="mt-1 text-xs text-[#8491a5]">Simple products use one default variant for SKU, pricing, and stock.</p></div><span class="rounded-full bg-[#eef4ff] px-2.5 py-1 text-[11px] font-bold text-[#1769e8]">Required fields marked *</span></div>
                    <div class="grid gap-4 md:grid-cols-2">
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550]">Product Name <span class="text-[#ef2c35]">*</span><x-ui.input wire:model.live="name" placeholder="Enter product name" class="!rounded-lg" controlClass="!rounded-lg !border-[#dfe6ef] !bg-white" /></label>
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550]">Slug <span class="text-[#ef2c35]">*</span><x-ui.input wire:model.live="slug" placeholder="Enter product slug" class="!rounded-lg" controlClass="!rounded-lg !border-[#dfe6ef] !bg-white" /></label>
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550]">Product Type <span class="text-[#ef2c35]">*</span><x-ui.select wire:model.live="product_type" placeholder="Select product type" class="!w-full"><x-ui.select.option value="simple">Simple</x-ui.select.option><x-ui.select.option value="variable">Variable</x-ui.select.option></x-ui.select></label>
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550]">Brand<x-ui.select wire:model.live="brand_id" placeholder="Select brand" clearable class="!w-full"><x-ui.select.option value="">None</x-ui.select.option>@foreach ($brands as $brand)<x-ui.select.option value="{{ $brand->id }}">{{ $brand->name }}</x-ui.select.option>@endforeach</x-ui.select></label>
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550] md:col-span-2">Primary Category<x-ui.select wire:model.live="primary_category_id" placeholder="Select category" clearable class="!w-full"><x-ui.select.option value="">None</x-ui.select.option>@foreach ($categories as $category)<x-ui.select.option value="{{ $category->id }}">{{ $category->name }}</x-ui.select.option>@endforeach</x-ui.select></label>
                        <label class="space-y-1.5 text-sm font-semibold text-[#263550] md:col-span-2">Short Description <span class="text-[#ef2c35]">*</span><x-ui.textarea wire:model.live="short_description" rows="3" maxlength="160" resize="vertical" placeholder="Enter a short description about the product..." class="!rounded-lg !border-[#dfe6ef]" /><span class="block text-right text-[11px] font-normal text-[#9aa8bd]">Maximum 160 characters</span></label>
                        <div class="md:col-span-2"><div class="mb-1.5 text-sm font-semibold text-[#263550]">Product Description</div><x-app.rich-text-editor :value="$description_json" /></div>
                    </div>
                </section>

                <section class="rounded-xl border border-[#dfe6ef] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.03)] sm:p-6"><div class="mb-5"><h2 class="font-bold">Pricing</h2><p class="mt-1 text-xs text-[#8491a5]">Prices are stored in minor currency units for precision.</p></div><div class="grid gap-4 sm:grid-cols-3"><label class="space-y-1.5 text-sm font-semibold text-[#263550]">Regular Price <span class="text-[#ef2c35]">*</span><x-ui.input type="number" min="0" wire:model.live="regular_price_minor" placeholder="0.00" class="!rounded-lg" controlClass="!rounded-lg !border-[#dfe6ef] !bg-white" /></label><label class="space-y-1.5 text-sm font-semibold text-[#263550]">Sale Price<x-ui.input type="number" min="0" wire:model.live="sale_price_minor" placeholder="0.00" class="!rounded-lg" controlClass="!rounded-lg !border-[#dfe6ef] !bg-white" /></label><label class="space-y-1.5 text-sm font-semibold text-[#263550]">Cost Price<x-ui.input type="number" min="0" wire:model.live="cost_price_minor" placeholder="0.00" class="!rounded-lg" controlClass="!rounded-lg !border-[#dfe6ef] !bg-white" /></label></div></section>
            </div>

            <section class="rounded-xl border border-[#dfe6ef] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.03)]"><h2 class="font-bold">Product Images</h2><p class="mt-1 text-xs text-[#8491a5]">Upload a main product image.</p><label class="mt-4 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#cfd9e7] bg-[#fbfcfe] px-4 text-center hover:border-[#1769e8] hover:bg-[#f6f9ff]"><svg class="size-9 text-[#1769e8]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M12 16V4m0 0L8 8m4-4 4 4"/><path d="M5 13v5a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-5"/></svg><span class="mt-3 text-sm font-semibold text-[#53627b]">Drag and drop or browse</span><span class="mt-1 text-[11px] text-[#9aa8bd]">PNG, JPG, or WEBP up to 5MB</span><input type="file" wire:model="image" accept="image/*" class="sr-only"></label><div wire:loading wire:target="image" class="mt-2 text-center text-xs font-semibold text-[#1769e8]">Uploading image...</div><button type="button" class="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-[#dce4ef] px-3 py-2.5 text-xs font-bold text-[#1769e8]"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 5h16v14H4z"/><circle cx="9" cy="10" r="1.5"/><path d="m5 17 4-4 3 3 2-2 5 4"/></svg>Add from Media Library</button></section>

            <div class="space-y-5">
                <section class="rounded-xl border border-[#dfe6ef] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.03)]"><h2 class="font-bold">Product Status</h2><label class="mt-4 block space-y-1.5 text-sm font-semibold text-[#263550]">Status<x-ui.select wire:model.live="status" placeholder="Select status" class="!w-full"><x-ui.select.option value="draft">Draft</x-ui.select.option><x-ui.select.option value="published">Published</x-ui.select.option><x-ui.select.option value="archived">Archived</x-ui.select.option></x-ui.select></label><label class="mt-4 block space-y-1.5 text-sm font-semibold text-[#263550]">Visibility<x-ui.select wire:model.live="visibility" placeholder="Select visibility" class="!w-full"><x-ui.select.option value="visible">Visible</x-ui.select.option><x-ui.select.option value="hidden">Hidden</x-ui.select.option></x-ui.select></label><label class="mt-4 flex items-center gap-3 text-sm font-semibold text-[#263550]"><input type="checkbox" wire:model.live="is_featured" class="size-4 rounded border-[#cbd5e1] text-[#1769e8] focus:ring-[#1769e8]"><span>Featured Product</span></label></section>
                <section class="rounded-xl border border-[#dfe6ef] bg-white p-5 shadow-[0_3px_12px_rgba(30,55,90,.03)]"><div class="flex items-center justify-between"><h2 class="font-bold">Categories</h2><span class="text-[#ef2c35]">*</span></div><p class="mt-1 text-xs text-[#8491a5]">Choose the primary storefront category above.</p><div class="mt-4 space-y-2">@forelse($categories->take(8) as $category)<label class="flex items-center gap-3 rounded-lg px-2 py-2 text-sm text-[#53627b] hover:bg-[#f5f8fc]"><input type="checkbox" @checked($primary_category_id === $category->id) wire:click="$set('primary_category_id', {{ $category->id }})" class="size-4 rounded border-[#cbd5e1] text-[#1769e8] focus:ring-[#1769e8]"><span>{{ $category->name }}</span></label>@empty<p class="text-sm text-[#9aa8bd]">Create categories before assigning products.</p>@endforelse</div></section>
            </div>
        </form>
    </div>
</div>
