<div class="p-5 sm:p-8">
    <div class="mx-auto max-w-[1480px]">
        <x-admin.cms.page-header eyebrow="StoreZ / Content / Announcements" title="Announcements" description="Keep customers informed with scheduled, dismissible storefront messaging.">
            <x-slot:actions><button wire:click="saveAnnouncement" wire:loading.attr="disabled" wire:target="saveAnnouncement" class="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm disabled:opacity-60"><x-ui.icon name="plus" class="size-4" /><span wire:loading.remove wire:target="saveAnnouncement">Save announcement</span><span wire:loading wire:target="saveAnnouncement">Saving...</span></button></x-slot:actions>
        </x-admin.cms.page-header>
        @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif

        <div class="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($stats as $label => $value)<x-admin.cms.stat-card :label="$label" :value="number_format($value)" :accent="$loop->iteration === 2 ? 'green' : ($loop->iteration === 3 ? 'orange' : 'blue')"><x-ui.icon name="megaphone" class="size-5" /></x-admin.cms.stat-card>@endforeach</div>
        <x-admin.cms.tabs><x-admin.cms.tab :active="true">All announcements</x-admin.cms.tab><x-admin.cms.tab>Published</x-admin.cms.tab><x-admin.cms.tab>Scheduled</x-admin.cms.tab><x-admin.cms.tab>Archived</x-admin.cms.tab></x-admin.cms.tabs>

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
            <div class="space-y-5">
                <x-admin.cms.toolbar><div class="relative flex-1"><x-ui.icon name="magnifying-glass" class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input wire:model.live.debounce.300ms="search" placeholder="Search announcements..." class="w-full rounded-lg border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm"></div><button wire:click="$set('search', '')" class="px-3 py-2 text-sm font-bold text-slate-500">Reset</button></x-admin.cms.toolbar>
                <x-admin.cms.panel><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-slate-100 text-[11px] uppercase tracking-wide text-slate-400"><tr><th class="px-4 py-3">Announcement</th><th class="px-4 py-3">Placement</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Window</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($announcements as $announcement)<tr wire:key="announcement-{{ $announcement->id }}" class="hover:bg-slate-50"><td class="px-4 py-4"><p class="font-bold text-slate-800">{{ $announcement->internal_title }}</p><p class="mt-1 max-w-md truncate text-xs text-slate-500">{{ $announcement->message }}</p></td><td class="px-4 py-4 text-slate-600">{{ str_replace('_', ' ', ucfirst($announcement->placement)) }}</td><td class="px-4 py-4"><x-admin.cms.badge :tone="$announcement->status === 'published' ? 'success' : ($announcement->status === 'scheduled' ? 'warning' : 'neutral')">{{ ucfirst($announcement->status) }}</x-admin.cms.badge></td><td class="px-4 py-4 text-xs text-slate-500">{{ $announcement->starts_at?->format('M d, Y') ?? 'Always' }}</td><td class="px-4 py-4 text-right"><button wire:click="deleteAnnouncement({{ $announcement->id }})" wire:confirm="Delete this announcement?" wire:loading.attr="disabled" wire:target="deleteAnnouncement({{ $announcement->id }})" class="font-bold text-red-600 disabled:opacity-60">Delete</button></td></tr>@empty<tr><td colspan="5" class="px-4 py-14 text-center text-sm text-slate-500">No announcements match your search.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $announcements->links() }}</div></x-admin.cms.panel>
            </div>
            <x-admin.cms.panel title="Create announcement" description="Draft a message, choose its placement, and schedule its visibility."><div class="space-y-4"><label class="block text-sm font-semibold text-slate-700">Internal title<input wire:model.live="internal_title" placeholder="Campaign or notice name" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold text-slate-700">Message<textarea wire:model.live="message" rows="4" placeholder="What should customers know?" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></textarea></label><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><label class="text-sm font-semibold text-slate-700">Style<select wire:model.live="style" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="danger">Danger</option></select></label><label class="text-sm font-semibold text-slate-700">Placement<select wire:model.live="placement" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="top_bar">Top bar</option><option value="storefront">Storefront</option><option value="checkout">Checkout</option><option value="account">Account</option></select></label></div><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><input wire:model.live="starts_at" type="datetime-local" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="Starts at"><input wire:model.live="ends_at" type="datetime-local" class="rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="Ends at"></div><label class="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" wire:model.live="dismissible" class="rounded border-slate-300 text-blue-600"> Allow customers to dismiss</label><button wire:click="saveAnnouncement" wire:loading.attr="disabled" wire:target="saveAnnouncement" class="w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">Save draft</button></div></x-admin.cms.panel>
        </div>
    </div>
</div>
