<div class="p-5 sm:p-8">
    <div class="mx-auto max-w-[1280px]">
        <div class="mb-5">
            <x-admin.cms.page-header eyebrow="StoreZ / Content / Banners / {{ $bannerId ? 'Edit' : 'Create' }}" :title="$bannerId ? 'Edit banner' : 'Create banner'" description="Build a responsive campaign banner with a clear destination and publication window."><x-slot:actions><a href="{{ url('/admin/content/banners') }}" class="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Cancel</a><button wire:click="saveBanner" wire:loading.attr="disabled" class="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60"><x-ui.icon name="check" class="size-4 !text-white" /> {{ $bannerId ? 'Update banner' : 'Save banner' }}</button></x-slot:actions></x-admin.cms.page-header>
        </div>
        @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
            <div class="space-y-5">
                <x-admin.cms.panel title="Banner information" description="The internal name helps your team identify this campaign. The title and description are customer-facing.">
                    <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold text-slate-700">Internal name<input wire:model.live="name" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-700">Placement<select wire:model.live="placement" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="hero">Hero</option><option value="homepage">Homepage promotion</option><option value="category">Category</option><option value="offers">Offers</option><option value="global">Global</option></select></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Eyebrow<input wire:model.live="eyebrow" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="StoreZ everyday value"></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Headline<input wire:model.live="title" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="A compelling campaign headline"></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Description<textarea wire:model.live="description" rows="4" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="Supporting campaign message"></textarea></label><label class="text-sm font-semibold text-slate-700">CTA label<input wire:model.live="cta_label" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="Shop now"></label><label class="text-sm font-semibold text-slate-700">Fallback theme<select wire:model.live="theme" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="blue">Blue</option><option value="red">Red</option><option value="green">Green</option><option value="amber">Amber</option></select></label><label class="text-sm font-semibold text-slate-700">Destination type<select wire:model.live="destination_type" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="url">Custom URL</option><option value="page">Page</option><option value="category">Category</option><option value="brand">Brand</option><option value="product">Product</option></select></label><label class="text-sm font-semibold text-slate-700 sm:col-span-2">Destination @if($destination_type === 'url')<input wire:model.live="destination_value" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="https://...">@else<select wire:model.live="destination_value" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="">Choose a target</option>@foreach($targetOptions[$destination_type] ?? [] as $target)<option wire:key="banner-target-{{ $destination_type }}-{{ $target->id }}" value="{{ $target->id }}">{{ $target->title ?? $target->name }}</option>@endforeach</select>@endif</label></div>
                </x-admin.cms.panel>
                {{-- Hero side image: upload a new asset or use the saved preview. --}}<x-admin.cms.panel title="Hero side media" description="Choose the image that appears beside hero copy on desktop and below it on mobile.">@if($placement === 'hero')<div class="grid gap-4 md:grid-cols-2"><div>{{-- Shared Media Library selection is intentionally disabled for Hero side images. --}}<div class="mt-3 rounded-lg border border-dashed border-slate-300 bg-slate-50 p-3">@if($side_image_file)<img src="{{ $side_image_file->temporaryUrl() }}" alt="Selected side image preview" class="mb-3 h-32 w-full rounded-md object-contain bg-white">@elseif($previewSideUrl)<img src="{{ $previewSideUrl }}" alt="{{ $title ?: 'Hero side image' }}" class="mb-3 h-32 w-full rounded-md object-contain bg-white">@endif<label for="hero-side-image-upload" class="text-xs font-bold text-slate-700">Upload a new side image</label><input id="hero-side-image-upload" type="file" wire:model="side_image_file" accept="image/*" class="mt-2 block w-full text-xs text-slate-600 file:mr-3 file:rounded-md file:border-0 file:bg-blue-600 file:px-3 file:py-2 file:text-xs file:font-bold file:text-white hover:file:bg-blue-700"><div class="mt-2 flex items-center gap-3"><button type="button" wire:click="uploadSideImage" wire:loading.attr="disabled" class="rounded-md bg-slate-900 px-3 py-2 text-xs font-bold text-white disabled:opacity-60">Upload and use image</button><span wire:loading wire:target="side_image_file,uploadSideImage" class="text-xs text-slate-500">Uploading...</span></div>@error('side_image_file')<p class="mt-2 text-xs text-red-600">{{ $message }}</p>@enderror</div>@if($side_media_id)<button type="button" wire:click="clearSideMedia" class="mt-2 text-xs font-bold text-red-600 hover:text-red-700">Remove side image</button>@endif</div><label class="text-sm font-semibold text-slate-700">Side image style<select wire:model.live="side_image_mode" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="cutout">Transparent cutout</option><option value="contained">Contained artwork</option></select><span class="mt-1 block text-xs font-normal text-slate-500">Choose how the image is displayed beside the hero copy.</span></label></div>@else<p class="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Side image settings are available for Hero banners only.</p>@endif</x-admin.cms.panel>
                <x-admin.cms.panel title="Schedule and ordering"><div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-semibold text-slate-700">Starts at<input type="datetime-local" wire:model.live="starts_at" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-700">Ends at<input type="datetime-local" wire:model.live="ends_at" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-semibold text-slate-700">Sort order<input type="number" min="0" wire:model.live="sort_order" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label></div></x-admin.cms.panel>
            </div>
            <div class="contents">
                <x-admin.cms.panel title="Publishing" description="Control when this banner can be shown publicly."><label class="text-sm font-semibold text-slate-700">Status<select wire:model.live="status" class="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="published">Published</option><option value="archived">Archived</option></select></label><div class="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">Published banners respect their start and end timestamps and placement rules.</div></x-admin.cms.panel>
                <x-admin.cms.panel class="xl:col-span-2" title="Live preview" description="This preview uses the current unsaved form values."><a href="{{ $previewUrl }}" class="group relative block min-h-56 overflow-hidden rounded-xl bg-gradient-to-br from-blue-700 to-blue-950 text-white" @if($previewUrl === '#') aria-disabled="true" @endif>@if($placement === 'hero' && $previewSideUrl)<div class="relative grid min-h-56 items-center gap-4 p-5 sm:grid-cols-[minmax(0,1fr)_minmax(120px,0.8fr)]"><div class="relative z-10 min-w-0"><p class="text-xs font-bold uppercase tracking-wide text-blue-200">{{ $eyebrow ?: ucfirst($placement) }}</p><h2 class="mt-1 text-xl font-black">{{ $title ?: 'Banner headline' }}</h2>@if($description)<p class="mt-1 text-sm text-white/80">{{ $description }}</p>@endif @if($cta_label)<span class="mt-3 inline-flex w-fit rounded-md bg-white px-3 py-2 text-xs font-bold text-slate-900">{{ $cta_label }}</span>@endif</div><div class="relative order-last flex min-h-32 items-center justify-center {{ $side_image_mode === 'contained' ? 'rounded-lg bg-white/10 p-2' : '' }}"><img src="{{ $previewSideUrl }}" alt="{{ $title ?: 'Banner preview' }}" class="max-h-40 w-full object-contain"></div></div>@else<picture>@if($previewMobileUrl)<source media="(max-width: 639px)" srcset="{{ $previewMobileUrl }}">@endif @if($previewDesktopUrl)<img src="{{ $previewDesktopUrl }}" alt="{{ $title ?: 'Banner preview' }}" class="absolute inset-0 size-full object-cover opacity-70 transition group-hover:scale-105">@endif</picture><div class="relative flex min-h-56 flex-col justify-end bg-gradient-to-t from-black/80 to-transparent p-5"><p class="text-xs font-bold uppercase tracking-wide text-blue-200">{{ $eyebrow ?: ucfirst($placement) }}</p><h2 class="mt-1 text-xl font-black">{{ $title ?: 'Banner headline' }}</h2>@if($description)<p class="mt-1 text-sm text-white/80">{{ $description }}</p>@endif @if($cta_label)<span class="mt-3 inline-flex w-fit rounded-md bg-white px-3 py-2 text-xs font-bold text-slate-900">{{ $cta_label }}</span>@endif</div>@endif</a><p class="mt-3 text-xs text-slate-500">Media, copy, placement, and CTA update as you edit the form.</p></x-admin.cms.panel>
            </div>
        </div>
    </div>
</div>
