<div class="p-5 sm:p-8"><div class="mx-auto max-w-[1100px]">
    <div class="mb-6"><p class="text-sm text-[#64748b]">StoreZ / Catalog / Categories / Import</p><h1 class="mt-1 text-[28px] font-extrabold tracking-tight text-[#111827]">Import Categories</h1><p class="mt-1 text-sm text-[#64748b]">Upload, validate, and import category hierarchy data from CSV.</p></div>
    <div class="mb-5 flex gap-2"><a href="{{ url('/admin/catalog/categories') }}" class="rounded-lg border border-[#e5e7eb] bg-white px-4 py-2.5 text-sm font-semibold text-[#374151]">Back to Categories</a></div>
    @if($errors->any())<div class="mb-5 rounded-lg border border-[#fecaca] bg-[#fef2f2] px-4 py-3 text-sm text-[#b91c1c]">{{ $errors->first() }}</div>@endif
    <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div class="space-y-5">
        <div class="rounded-xl border border-[#e5e7eb] bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-sm font-bold text-[#111827]">Import Progress</h2><span class="text-xs text-[#64748b]">Step {{ $step }} of 4</span></div><div class="mt-4 grid grid-cols-4 gap-2">@foreach(['Upload','Review','Validate','Complete'] as $index=>$label)<div><div class="h-2 rounded-full {{ $step > $index ? 'bg-[#2563eb]' : 'bg-[#e5e7eb]' }}"></div><p class="mt-1 text-[10px] text-[#64748b]">{{ $label }}</p></div>@endforeach</div></div>
        @if($step === 1)<div class="rounded-xl border border-[#e5e7eb] bg-white p-5 shadow-sm"><h2 class="text-sm font-bold text-[#111827]">Upload Category CSV</h2><label class="mt-4 flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#cbd5e1] bg-[#f8fafc] text-center hover:border-[#2563eb]"><svg class="size-8 text-[#2563eb]" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5"/></svg><span class="mt-2 text-sm font-semibold text-[#374151]">Choose a CSV file</span><span class="mt-1 text-xs text-[#64748b]">Maximum 10 MB</span><input type="file" wire:model="file" accept=".csv,.txt" class="sr-only"></label>@error('file')<p class="mt-2 text-xs text-red-600">{{ $message }}</p>@enderror<div class="mt-5"><p class="text-xs font-bold text-[#374151]">Import mode</p><div class="mt-2 space-y-2 text-sm text-[#374151]"><label class="flex gap-2"><input type="radio" wire:model="mode" value="create"> Create new categories</label><label class="flex gap-2"><input type="radio" wire:model="mode" value="update_by_slug"> Update existing categories by slug</label></div></div><button wire:click="upload" class="mt-5 rounded-lg bg-[#2563eb] px-4 py-2.5 text-sm font-bold text-white">Upload and Review</button></div>@endif
        @if($step >= 2)<div class="rounded-xl border border-[#e5e7eb] bg-white p-5 shadow-sm"><h2 class="text-sm font-bold text-[#111827]">{{ $import?->filename }}</h2><p class="mt-1 text-xs text-[#64748b]">Mode: {{ $import?->mode === 'create' ? 'Create new categories' : 'Update by slug' }}</p>@if($step === 2)<button wire:click="validateRows" class="mt-5 rounded-lg bg-[#2563eb] px-4 py-2.5 text-sm font-bold text-white">Validate CSV</button>@elseif($step === 3)<div class="mt-5 grid grid-cols-3 gap-3"><div class="rounded-lg bg-[#eff6ff] p-3 text-center"><p class="text-xl font-extrabold text-[#2563eb]">{{ $summary['rows'] ?? 0 }}</p><p class="text-xs text-[#64748b]">Rows</p></div><div class="rounded-lg bg-[#ecfdf5] p-3 text-center"><p class="text-xl font-extrabold text-[#16a34a]">{{ $summary['valid'] ?? 0 }}</p><p class="text-xs text-[#64748b]">Valid</p></div><div class="rounded-lg bg-[#fef2f2] p-3 text-center"><p class="text-xl font-extrabold text-[#dc2626]">{{ $summary['errors'] ?? 0 }}</p><p class="text-xs text-[#64748b]">Errors</p></div></div>@if(!empty($summary['error_rows']))<div class="mt-4 space-y-2">@foreach($summary['error_rows'] as $line=>$messages)<div class="rounded-lg bg-[#fef2f2] px-3 py-2 text-xs text-[#b91c1c]"><strong>Row {{ $line }}:</strong> {{ implode(' ', $messages) }}</div>@endforeach</div>@endif@if(($summary['errors'] ?? 1) === 0)<button wire:click="runImport" class="mt-5 rounded-lg bg-[#16a34a] px-4 py-2.5 text-sm font-bold text-white">Confirm Import</button>@endif @elseif($step === 4)<div class="mt-5 rounded-lg bg-[#ecfdf5] p-4 text-sm text-[#166534]">Import complete: {{ $summary['created'] ?? 0 }} created and {{ $summary['updated'] ?? 0 }} updated.</div><a href="{{ url('/admin/catalog/categories') }}" class="mt-5 inline-block rounded-lg bg-[#2563eb] px-4 py-2.5 text-sm font-bold text-white">View Categories</a>@endif</div>@endif
    </div><aside class="space-y-5"><div class="rounded-xl border border-[#e5e7eb] bg-white p-5 shadow-sm"><h2 class="text-sm font-bold text-[#111827]">CSV fields</h2><p class="mt-2 text-xs leading-5 text-[#64748b]">Required: <strong>name</strong>. Optional: slug, parent_slug, description, is_active, sort_order.</p></div><div class="rounded-xl border border-[#e5e7eb] bg-white p-5 shadow-sm"><h2 class="text-sm font-bold text-[#111827]">Hierarchy rules</h2><p class="mt-2 text-xs leading-5 text-[#64748b]">Parent slugs must exist in the catalog or the same CSV. Circular references and nesting beyond four levels are rejected before import.</p></div></aside></div>
</div></div>
