<div class="p-5 sm:p-8">
    <div class="mx-auto max-w-[1280px]">
        <x-admin.cms.page-header eyebrow="StoreZ / Content / Header" title="Header settings" description="Configure the storefront header while keeping the real customer experience in view."><x-slot:actions><button wire:click="saveHeader" wire:loading.attr="disabled" wire:target="saveHeader" class="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm disabled:opacity-60"><x-ui.icon name="check" class="size-4" /><span wire:loading.remove wire:target="saveHeader">Save header</span><span wire:loading wire:target="saveHeader">Saving...</span></button></x-slot:actions></x-admin.cms.page-header>
        @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <div class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]">
            <div class="space-y-5"><x-admin.cms.panel title="Branding" description="Choose a shared logo asset or provide a fallback URL."><div class="space-y-4"><label class="block text-sm font-semibold text-slate-700">Logo URL<input wire:model.live="logo_url" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="https://..."></label><x-admin.media-picker :assets="$mediaAssets" :selected="$logo_media_id" title="Header logo" context="header_logo" /><label class="block text-sm font-semibold text-slate-700">Support text<input wire:model.live="support_text" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" placeholder="Need help? Call us"></label></div></x-admin.cms.panel><x-admin.cms.panel title="Header behavior"><div class="space-y-3"><label class="flex items-center justify-between gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><span>Show search</span><input type="checkbox" wire:model.live="show_search" class="rounded border-slate-300 text-blue-600"></label><label class="flex items-center justify-between gap-3 rounded-lg border border-slate-200 p-3 text-sm font-semibold"><span>Sticky header</span><input type="checkbox" wire:model.live="sticky" class="rounded border-slate-300 text-blue-600"></label></div></x-admin.cms.panel></div>
            <x-admin.cms.panel title="Header preview" description="Representative preview of the storefront component."><div class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center gap-3 border-b border-slate-100 px-4 py-4"><div class="grid size-9 place-items-center rounded-lg bg-blue-50 text-xs font-extrabold text-blue-700">SZ</div><div class="h-8 flex-1 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-400">{{ $show_search ? 'Search for products, brands and more' : 'StoreZ storefront' }}</div><span class="text-slate-400">♡</span><span class="text-slate-400">🛒</span></div><div class="p-5 text-center text-xs text-slate-500">{{ $support_text ?: 'Your support message appears here.' }}</div></div><p class="mt-3 text-xs text-slate-500">Open the storefront preview to verify responsive behavior.</p></x-admin.cms.panel>
        </div>
    </div>
</div>
