@props(['categories' => []])

<footer class="bg-store-navy text-slate-200">
    <x-store.ui.container class="py-10">
        <div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-5">
            <div><h2 class="text-base font-bold text-white">About StoreZ</h2><p class="mt-3 text-sm leading-6 text-blue-100">Your trusted online shopping destination in Bangladesh.</p><div class="mt-4 flex gap-3"><a href="#facebook" aria-label="Facebook" class="text-blue-100 hover:text-white">Facebook</a><a href="#instagram" aria-label="Instagram" class="text-blue-100 hover:text-white">Instagram</a></div></div>
            <div><h2 class="text-base font-bold text-white">Customer Service</h2><ul class="mt-3 space-y-2 text-sm"><li><a href="#help" class="hover:text-white">Help Center</a></li><li><a href="#returns" class="hover:text-white">Returns & Refunds</a></li><li><a href="#shipping" class="hover:text-white">Shipping Info</a></li><li><a href="#contact" class="hover:text-white">Contact Us</a></li></ul></div>
            <div><h2 class="text-base font-bold text-white">My Account</h2><ul class="mt-3 space-y-2 text-sm"><li><a href="#orders" class="hover:text-white">My Orders</a></li><li><a href="#wishlist" class="hover:text-white">Wishlist</a></li><li><a href="#track" class="hover:text-white">Track Order</a></li><li><a href="#settings" class="hover:text-white">Account Settings</a></li></ul></div>
            <div><h2 class="text-base font-bold text-white">Popular Categories</h2><ul class="mt-3 space-y-2 text-sm">@foreach (array_slice($categories, 0, 4) as $category)<li><a href="#{{ $category['slug'] }}" class="hover:text-white">{{ $category['name'] }}</a></li>@endforeach</ul></div>
            <div><h2 class="text-base font-bold text-white">Stay in the loop</h2><p class="mt-3 text-sm leading-6">Get offers and product updates in your inbox.</p><form class="mt-4 flex" action="#newsletter"><label for="newsletter-email" class="sr-only">Email address</label><input id="newsletter-email" type="email" placeholder="Your email" class="min-w-0 flex-1 rounded-l-control border-0 bg-white px-3 py-2 text-sm text-store-ink placeholder:text-store-muted outline-none focus:ring-2 focus:ring-store-blue"><button class="rounded-r-control bg-store-blue px-4 text-sm font-semibold text-white hover:bg-store-blue-dark">Subscribe</button></form></div>
        </div>
        <div class="mt-10 flex flex-col gap-3 border-t border-white/15 pt-5 text-xs sm:flex-row sm:items-center sm:justify-between"><p>© {{ now()->year }} StoreZ. All rights reserved.</p><div class="flex gap-4"><a href="#terms" class="hover:text-white">Terms & Conditions</a><a href="#privacy" class="hover:text-white">Privacy Policy</a></div><span class="font-semibold text-white">Visa · Mastercard · bKash · Nagad · COD</span></div>
    </x-store.ui.container>
</footer>
