<div class="p-5 sm:p-8">
    <div class="mx-auto max-w-[1480px]">
        <x-admin.cms.page-header eyebrow="StoreZ / Content / Navigation" title="Navigation manager" description="Organize storefront menus, nested links, and internal destinations from one place.">
            <x-slot:actions><button wire:click="saveMenu" wire:loading.attr="disabled" wire:target="saveMenu" class="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm disabled:opacity-60"><x-ui.icon name="check" class="size-4" /><span wire:loading.remove wire:target="saveMenu">Save menu</span><span wire:loading wire:target="saveMenu">Saving...</span></button></x-slot:actions>
        </x-admin.cms.page-header>
        @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif

        <div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
            <x-admin.cms.panel title="{{ $menu?->name ?: 'Primary navigation' }}" description="Use the handles and order controls to maintain a clear hierarchy.">
                <div class="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-xs"><span class="font-bold text-slate-700">{{ $menu?->items?->count() ?? 0 }} top-level items</span><span class="text-slate-500">Location: {{ str_replace('_', ' ', ucfirst($location)) }}</span></div>
                <div class="space-y-2">
                    @forelse($menu?->items ?? [] as $item)
                        <div wire:key="menu-item-{{ $item->id }}" class="rounded-lg border border-slate-200 bg-white p-3 shadow-sm"><div class="flex items-center gap-3"><span class="cursor-grab text-slate-400" aria-label="Drag to reorder">⠿</span><span class="grid size-8 place-items-center rounded-md bg-blue-50 text-xs font-bold text-blue-700">{{ $loop->iteration }}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold text-slate-800">{{ $item->label }}</p><p class="truncate text-xs text-slate-500">{{ $item->type }} · {{ $item->url ?: ($item->targets->first()?->target?->slug ?? '⚠ Broken target') }}</p></div><span class="size-2 rounded-full {{ $item->enabled ? 'bg-emerald-500' : 'bg-slate-300' }}"></span><button wire:click="moveItem({{ $item->id }}, -1)" wire:loading.attr="disabled" wire:target="moveItem({{ $item->id }}, -1)" class="rounded px-2 py-1 text-xs font-bold text-slate-500 disabled:opacity-60">↑</button><button wire:click="moveItem({{ $item->id }}, 1)" wire:loading.attr="disabled" wire:target="moveItem({{ $item->id }}, 1)" class="rounded px-2 py-1 text-xs font-bold text-slate-500 disabled:opacity-60">↓</button><button wire:click="deleteItem({{ $item->id }})" wire:confirm="Delete this menu item?" wire:loading.attr="disabled" wire:target="deleteItem({{ $item->id }})" class="text-xs font-bold text-red-600 disabled:opacity-60">Delete</button></div>
                            @if($item->children->isNotEmpty())<div class="mt-3 space-y-2 border-l-2 border-slate-100 pl-9">@foreach($item->children as $child)<div wire:key="menu-child-{{ $child->id }}" class="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span class="text-slate-400">↳</span><span class="min-w-0 flex-1 truncate font-semibold text-slate-700">{{ $child->label }}</span><span class="text-[11px] text-slate-400">{{ $child->type }}</span><button wire:click="deleteItem({{ $child->id }})" wire:confirm="Delete this menu item?" wire:loading.attr="disabled" class="text-xs font-bold text-red-600 disabled:opacity-60">Remove</button></div>@endforeach</div>@endif
                        </div>
                    @empty
                        <div class="rounded-lg border border-dashed border-slate-300 px-4 py-12 text-center text-sm text-slate-500">No navigation items yet. Add your first item from the editor.</div>
                    @endforelse
                </div>
            </x-admin.cms.panel>
            <div class="space-y-5">
                <x-admin.cms.panel title="Menu settings" description="Configure the menu identity and storefront location."><div class="space-y-4"><label class="block text-sm font-semibold text-slate-700">Name<input wire:model.live="name" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold text-slate-700">Key<input wire:model.live="key" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold text-slate-700">Location<select wire:model.live="location" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="header_primary">Header primary</option><option value="mobile">Mobile</option><option value="footer_shop">Footer shop</option></select></label><button wire:click="saveMenu" wire:loading.attr="disabled" wire:target="saveMenu" class="w-full rounded-lg bg-slate-900 px-3 py-2.5 text-sm font-bold text-white disabled:opacity-60">Save settings</button></div></x-admin.cms.panel>
                <x-admin.cms.panel title="Add menu item" description="Link to a page, catalog record, route, or custom URL."><div class="space-y-3"><input wire:model.live="label" placeholder="Label" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><select wire:model.live="type" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="custom_url">Custom URL</option><option value="route">Named route</option><option value="page">Page</option><option value="category">Category</option><option value="brand">Brand</option><option value="product">Product</option></select>@if($type === 'custom_url')<input wire:model.live="url" placeholder="https://..." class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@elseif($type === 'route')<input wire:model.live="route_name" placeholder="Route name" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@else<input wire:model.live="target_id" type="number" placeholder="Target ID" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm">@endif<input wire:model.live="parent_id" type="number" placeholder="Parent item ID (optional)" class="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><label class="flex items-center gap-2 text-sm"><input type="checkbox" wire:model.live="enabled" class="rounded border-slate-300 text-blue-600"> Enabled</label><button wire:click="addItem" wire:loading.attr="disabled" wire:target="addItem" class="w-full rounded-lg bg-blue-600 px-3 py-2.5 text-sm font-bold text-white disabled:opacity-60"><span wire:loading.remove wire:target="addItem">Add item</span><span wire:loading wire:target="addItem">Adding...</span></button></div></x-admin.cms.panel>
            </div>
        </div>
    </div>
</div>
